
title = "CSV Source Files Configuration"

# Bucket root for all Storage Folders: {storage_prefix}/{report_type}_{version}/report_date=YYYY-MM-DD/
storage_prefix = "caravan-versioned"

# BigQuery configuration
[bigquery]
dataset = "youtube_analytics"

[file.claim_raw]
# example file: YouTube_SomeBrandName_M_20230601_claim_raw_v1-1.csv.tar.gz
is_enabled = true
exclude_file_name_base = "adj_claim_raw"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})' 
regex_group_names = ["content_owner", "file_date_key"]
# file_date_key is special and it will be converted to a eom report_date_key when found (for now)

[file.adj_claim_raw]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.asset_raw]
is_enabled = true
exclude_file_name_base = "adj_asset_raw"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.adj_asset_raw]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.video_raw]
is_enabled = true
exclude_file_name_base = "adj_video_raw"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.adj_video_raw]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.red_rawdata_asset]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.red_rawdata_video]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.red_music_rawdata_asset]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.red_music_rawdata_video]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.monthly_shorts_non_music_ads_video_summary]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.monthly_shorts_non_music_subscription_video_summary]
is_enabled = true
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[file.video_report]
is_enabled = true
regex_pattern = 'video_report_(.+)_V_(.+)\.csv'
regex_group_names = ["content_owner", "file_version"]
